version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-testing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d96b5tk7ut9m"
s3_prefix = "sam-testing"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
